// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:2492e5c9-3362-4c6b-9090-d7984040e85d",
    "aws_cognito_region": "us-west-2",
    "aws_mobile_analytics_app_id": "974be01499dd4d4bb757896ab851b8df",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
